version: '3.8'

services:
  web:
    build: .
    command: gunicorn video_platform.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - .env
    depends_on:
      - db
      - redis
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres.dyrirazjssnbxzfyxvjv
      - POSTGRES_PASSWORD=dicksuck228
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:6
  celery:
    build: .
    command: celery -A video_platform.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
  celery-beat:
    build: .
    command: celery -A video_platform.celery beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
  static_volume:
  media_volume: